# Generated by Django 2.1.5 on 2019-01-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay',
            name='id',
            field=models.AutoField(default='abc', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
