# Generated by Django 2.1.5 on 2019-01-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replay', '0002_replay_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
