# Generated by Django 2.1.5 on 2019-01-15 13:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('replay_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('song_title', models.CharField(max_length=32)),
                ('song_artist', models.CharField(max_length=32)),
                ('beatmap_creator', models.CharField(max_length=16)),
                ('beatmap_difficulty', models.CharField(max_length=32)),
                ('beatmap_od', models.DecimalField(decimal_places=1, max_digits=3)),
                ('rank_achieved', models.CharField(max_length=1)),
                ('pp', models.DecimalField(decimal_places=2, max_digits=6)),
                ('raw_accuracy', models.DecimalField(decimal_places=2, max_digits=4)),
                ('count_300', models.PositiveSmallIntegerField()),
                ('count_100', models.PositiveSmallIntegerField()),
                ('count_50', models.PositiveSmallIntegerField()),
                ('count_miss', models.PositiveSmallIntegerField()),
                ('ap', models.DecimalField(decimal_places=2, max_digits=6)),
                ('true_accuracy', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hit_error_array', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=5), size=None)),
                ('min_early_hit_error', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_early_hit_error', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mean_early_hit_error', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_late_hit_error', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_late_hit_error', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mean_late_hit_error', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_abs_hit_error', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_abs_hit_error', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mean_abs_hit_error', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
